config/routes.rb
Rails.application.routes.draw do
  root "pages#show", static_page: "home"
  get "/pages/*static_page", to: "pages#show"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to:"sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users, except: [:new, :destroy] do
    resources :relationships, only: [:index, :create, :destroy]
    resources :words, only: :index
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :active_relationships, class_name: Relationship.name,
    foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: Relationship.name,
    foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :lessons, dependent: :destroy

  attr_accessor :remember_token

  before_save :downcase_email

  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255}, 
    format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  validates :password, presence: true, length: {minimum: 6}, allow_nil: true

  has_secure_password

  class << self
    def digest string
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
      BCrypt::Password.create string, cost: cost
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def remember
    self.remember_token = User.new_token
    update_attributes remember_digest: User.digest(remember_token)
  end

  def forget
    update_attributes remember_digest: nil
  end

  def authenticated? attribute, token
    digest = send "#{attribute}_digest"
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password? token
  end
  
  def current_user? current_user
    self == current_user
  end

  def feeds
    Lesson.following_by(self).updated_at_desc
  end

  def follow other_user
    active_relationships.create followed_id: other_user.id
  end

  def unfollow other_user
    following.delete other_user
  end

  def following? other_user
    following.include? other_user
  end

  private
  def downcase_email
    self.email.downcase!
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:show, :edit, :update]
  before_action :find_user, only: [:show, :edit, :update]
  before_action :correct_user, only: [:edit, :update]

  def index
    @users = User.all.paginate page: params[:page], per_page: Settings.users.per_page
  end
  
  def new
    if logged_in?
      redirect_to current_user
    else
      @user = User.new
    end
  end

  def create
    @user = User.new user_params
    if @user.save
      log_in @user
      flash[:success] = t ".success_signup"
      redirect_to @user
    else
      render :new
    end
  end

  def show
    @lessons = @user.lessons.paginate page: params[:page], 
      per_page: Settings.lessons.per_page
    @relationship = current_user.active_relationships
      .find_by followed_id: @user.id
  end

  def edit
  end

  def update
    if @user.update_attributes user_params
      flash[:success] = t ".profile_updated"
      redirect_to @user
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit :name, :email, :password, 
      :password_confirmation
  end

  def find_user
    @user = User.find_by id: params[:id]
    unless @user
      flash[:danger] = t ".user_not_exist"
      redirect_to root_path
    end
  end

  def correct_user
    redirect_to root_url unless @user.current_user? current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for user, size: 80
    gravatar_id = Digest::MD5::hexdigest user.email.downcase
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}
      ?s=#{size}"
    image_tag gravatar_url, alt: user.name, class: "gravatar"
  end
end

app/views/users/_follow.html.erb
<%= form_for :relationships, url: user_relationships_path(user_id:
  current_user.id), remote: true do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit t(".follow"), class: "btn btn-primary" %>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :password %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for :relationships, url: user_relationship_path(user_id:
  current_user.id, id: @relationship.id), html: {method: :delete},
  remote: true do |f| %>
  <%= f.submit t(".unfollow"), class: "btn btn-danger" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
</li>

app/views/users/edit.html.erb
<% provide :title, t(".title") %>
<% provide :button_text, t(".save_changes") %>
<h1><%= t ".update_profile" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">
        <%= t ".change_avatar" %></a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide :title, t(".title") %>
<h1><%= t ".title" %></h1>

<%= will_paginate %>
<ul class="users">
  <%= render @users %>
</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<% provide :title, t(".title") %>
<% provide :button_text, t(".create_account") %>
<h1><%= t ".title" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/users/show.html.erb
<% provide :title, @user.name %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user, size: 150 %>
        <%= @user.name %>
      </h1>
    </section>
    <section class="stats">
      <%= render "shared/stats" %>
    </section>
  </aside>
  <div class="col-md-8">
    <div class="main_content">
      <div id="follow_form">
        <% if logged_in? && !@user.current_user?(current_user) %>
          <% if current_user.following? @user %>
            <%= render "unfollow" %>
          <% else %>
            <%= render "follow" %>
          <% end %>
        <% end %>
      </div>
      <h3><%=t ".activities" %> (<%= pluralize @user.lessons.count, t(".lesson")
        %>)</h3>
      <div class="activities">
        <%= render "shared/activities" %>
      </div>
    </div>
  </div>
</div>