config/routes.rb
Rails.application.routes.draw do
  root "pages#show", static_page: "home"
  get "/pages/*static_page", to: "pages#show"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to:"sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users, except: [:new, :destroy] do
    resources :relationships, only: [:index, :create, :destroy]
    resources :words, only: :index
  end
end

app/views/shared/_activities.html.erb
<% if @lessons.any? %>
  <ol class="lessons">
    <%= render @lessons %>
  </ol>
  <%= will_paginate @lessons %>
<% end %>

app/views/shared/_categories_list.html.erb
<div class="digg_pagination">
  <div class="page_pagination_info">
    <%= page_entries_info @categories %>
  </div>
  <%= paginate @categories %>
</div>
<% if @categories.any? %>
  <%= render @categories %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t ".form_contains" %> <%= pluralize object.errors.count, 
        t(".error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_stats.html.erb
<div class="stats">
  <div class="learned_info">
    <%= link_to user_words_path @user do %>
      <span>
        <%= t(".learned") %>
        <%= pluralize Word.learned_by(current_user).count, t(".word") %>
      </span>
    <% end %>
  </div>
  <div class="follow_info">
    <%= link_to user_relationships_path user_id: @user.id,
      relationship: "following" do %>
      <strong id="following" class="stat">
        <%= @user.following.count %>
      </strong>
      <%= t ".following" %>
    <% end %>
    <%= link_to user_relationships_path user_id: @user.id, 
      relationship: "followers" do %>
      <strong id="followers" class="stat">
        <%= @user.followers.count %>
      </strong>
      <%= t ".followers" %>
    <% end %>
  </div>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(@user, size: 150), @user %>
<h1><%= @user.name %></h1>
<span><%= link_to t(".view_profile"), @user %></span>

app/views/shared/_words_list.html.erb
<div class="digg_pagination">
  <div class="page_pagination_info">
    <%= page_entries_info @words %>
  </div>
  <%= paginate @words %>
</div>
<div class="row">
  <% @words.in_groups(2, false).each do |words| %>
    <% if words.any? %>
      <div class="col-md-6">
        <ul class="words">
          <li>
            <span class="col-md-4"><%= t ".japanese" %></span>
            <span class="col-md-4"><%= t ".vietnamese" %></span>
          </li>
          <%= render words %>
        </ul>
      </div>
    <% end %>
  <% end %>
</div>
<div class="digg_pagination">
  <%= paginate @words %>
</div>