config/routes.rb
Rails.application.routes.draw do
  root "pages#show", static_page: "home"
  get "/pages/*static_page", to: "pages#show"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to:"sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users, except: [:new, :destroy] do
    resources :relationships, only: [:index, :create, :destroy]
    resources :words, only: :index
  end
end

app/views/pages/about.html.erb
<% provide :title, t(".title") %>
<h1><%= t ".title" %></h1>
<p>
  <%= t ".intro" %>
  <%= link_to t(".rails_tutorial"), "http://www.railstutorial.org/" %></a>.
</p>

app/views/pages/contact.html.erb
<% provide :title, t(".title") %>
<h1><%= t ".title" %></h1>
<p>
  <%= t ".contact_admin_at" %> 
  <%= link_to t(".facebok"), "https://www.facebook.com/ttluong1993" %></a>.
</p>

app/views/pages/help.html.erb
<% provide :title, t(".title") %>
<h1><%= t ".title" %></h1>
<p>
  <%= t ".get_help" %> 
  <%= link_to t(".help_page"), "http://www.railstutorial.org/help" %>. 
  <%= t ".get_book" %> 
  <em><%= link_to t(".rails_book"), "http://www.railstutorial.org/book" %></em>
</p>

app/views/pages/home.html.erb
<% provide :title, t(".title") %>
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render "shared/user_info" %>
      </section>
      <section class="stats">
        <%= render "shared/stats" %>
      </section>
    </aside>
    <div class="col-md-8">
      <div class="main_content">
        <%= link_to t(".words"), user_words_path(@user), class: "btn btn-huge btn-lg btn-info" %>
        <%= link_to t(".lesson"), "#", class: "btn btn-huge btn-lg btn-info" %>
        <h3><%=t ".activities" %></h3>
        <div class="activities">
          <%= render "shared/activities" %>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <%= link_to image_tag "Framgia-Logo.png" %>
    <h1><%= t ".center_logo" %></h1>
    <%= link_to t(".sign_up"), signup_path, class: "btn btn-lg btn-primary" %>
  </div>
<% end %>